version: '3.7'
services:
  blokus:
    container_name: tempgame
    build:
      context: ./tempgame/backend
    image: tempgate
    restart: always
    networks:
      - gamenet

  gateway:
    container_name: game_gateway
    build:
      context: ./gateway
    depends_on:
      - tempgame
    restart: always
    networks:
      - gamenet
    environment:
      - "TOKEN_SECRET=${GAME_TOKEN_SECRET}"

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - gateway
    volumes:
      - "${PWD}/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "443:443"
    networks:
      - gamenet

networks:
  gamenet: